cssLocators HW + Relative Locators
HeartlessHer0/TAF pull request #2
Opened 2022-04-23 15:03 UTC by HeartlessHer0

В классе SauseDeemoTests  потыкался с css локаторами
В классе Task_6 выполнил задание. Единственное что не получилось разбить тест на пункты. Когда делал разные тесты(например: Один тест где логин,а второй добавление в корзину) то во втором тесте не находило элементы).

2022-04-25 12:11 UTC, wildpioneer requested changes

2022-04-25 12:11 UTC, wildpioneer commented on src/test/java/tests/SauseDemoTests.java
> +
Это все по css locators? или еще не доделано?

2022-04-25 15:48 UTC, HeartlessHer0 commented
По cssLocators все
в Task_6 основное, где надо логиниться на сайте и добавлять товар в корзину

2022-04-25 19:03 UTC, HeartlessHer0 commented
Доделаю еще по xPath локаторам

2022-05-01 15:35 UTC, HeartlessHer0 commented
Потыкался с xPath , в целом все понял, единственное что некорректно работал поиск с использованием preceding-sibling. Когда на сайте проверял валодность элемент находило, а в тесте нет. класс Test_6 оставил как есть. В нем еще с прошлого раза остались относительные локаторы:   WebElement tshirtRed = driver.findElement(with(By.tagName("button")).below(bikeLight).below(By.id("add-to-cart-sauce-labs-fleece-jacket")));

2022-05-30 13:33 UTC, wildpioneer commented
Проверено

2022-05-30 13:33 UTC, closed without merging